apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealedsecret.yaml

helmCharts:
  - name: wordpress
    releaseName: loibiscom
    namespace: loibiscom
    repo: https://opssavvy.github.io/helmcharts
    version: 0.1.1
    valuesFile: ./values.yaml